config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  resources :menus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'menu#index'
  resources :menus do
    resources :comments
  end
  # Definroot "menu#index"es the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible
  belongs_to :menu
end

app/models/concerns/visible.rb
# frozen_string_literal: true

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  include Visible

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :price, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :menus

  #=================================================================
  # This part of the code below will validate the email in case the user will type something that will not corespond with the email syntax
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i
  # this checks for the presence of . and @ in email
  validates :email, length: { maximum: 255 },
                    presence: { message: "can't be empty" },
                    format: { with: VALID_EMAIL_REGEX, message: 'invalid format' },
                    uniqueness: { case_sensitive: false }
  #=================================================================


  enum role: %i[user moderator admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/models/view.rb
# frozen_string_literal: true

class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  # http_basic_authenticate_with name: 'user', password: 'secret', only: :destroy

  # Create a comment
  def create
    @menu = Menu.find(params[:menu_id])
    @comment = @menu.comments.create(comment_params)
    redirect_to menu_path(@menu)
  end

  # Destroy a comment
  def destroy
    @menu = Menu.find(params[:menu_id])
    @comment = @menu.comments.find(params[:id])
    @comment.destroy
    redirect_to menu_path(@menu), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/menu_controller.rb
# frozen_string_literal: true

# require 'uri'
require 'net/http'

class MenuController < ApplicationController
  def index
    # Weather API
    url = 'https://api.openweathermap.org/data/2.5/weather?lat=53.350140&lon=-6.266155&units=metric&appid=197128ae14d1b8c4d1779e83bd3c628e'

    uri = URI(url)
    res = Net::HTTP.get_response(uri)
    # puts res.body if res.is_a?(Net::HTTPSuccess)
    @data = JSON.parse(res.body)
    # console


    # Food menu API
    url2 = 'https://www.themealdb.com/api/json/v1/1/categories.php'

    uri2 = URI(url2)
    res2 = Net::HTTP.get_response(uri2)
    # puts res.body if res.is_a?(Net::HTTPSuccess)
    @foodmenu = JSON.parse(res2.body)
  end
end

app/controllers/menus_controller.rb
# frozen_string_literal: true

class MenusController < ApplicationController
  before_action :set_menu, only: %i[show edit update destroy]
  # http_basic_authenticate_with name: "menu", password: "secret", except: [:index, :show]
  before_action :authenticate_user!, except: %i[index show]

  # GET /menus or /menus.json
  def index
    # @menus = Menu.all
    @q = Menu.ransack(params[:q])
    @menus = @q.result
  end

  # GET /menus/1 or /menus/1.json
  def show
    @menu = Menu.find(params[:id])
    @q = Menu.ransack(params[:q])
    @menus = @q.result
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)

    # if @menu.save
    #   redirect_to @menu
    # else
    #   render :new, status: :unprocessable_entity
    # end

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menu_url(@menu), notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
    #====================================================================
    # @menu = Menu.find(params[:id])

    # if @menu.update(menu_params)
    #   redirect_to @menu
    # else
    #   render :edit, status: :unprocessable_entity
    # end
    #====================================================================
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy

    #===================================================
    # @menu = Menu.find(params[:id])
    # @menu.destroy

    # redirect_to root_path, status: :see_other
    #===================================================

    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
      #===================================================

      #===================================================
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu
    @menu = Menu.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def menu_params
    params.require(:menu).permit(:title, :body, :price, :user_id, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/menu_helper.rb
# frozen_string_literal: true

module MenuHelper
end

app/helpers/menus_helper.rb
# frozen_string_literal: true

module MenusHelper
end

app/views/comments/_comment.html.erb

<div class="card bg-light shadow-sm mb-2">
  <div class="card-body">
    
    <% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <% if current_user %>
    <% if current_user.admin? %>
      <p>
        <%= link_to "Destroy Comment", [comment.menu, comment], data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: "btn btn-danger " %>
      </p>
    <% end %>
  <% end %>
<% end %>


  </div>
</div>







app/views/comments/_form.html.erb
<%= form_with model: [ @menu, @menu.comments.build ] do |form| %>
  
  <p class="form-group">
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>

  <p class="form-group">
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, class:"form-control" %>
  </p>
  <p class="form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, class:"form-control" %>
  </p>
  <p>
    <%= form.submit class:"btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag "main" %>
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

   <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

  <!-- Template Main CSS File -->
  <link href="assets/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Yummy - v1.2.1
  * Template URL: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

    <title>Restaurant Menu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
<!-- Hew update-->
    <%= render "menu/header"%> 
    <div class="container" id="container">   
    <% if notice %>
      <%= render "layouts/alerts" %> 
    <% end %>
      <%= yield %>
    </div>
    <%= render "menu/footer"%> 
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

app/views/menu/_footer.html.erb
<!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Address</h4>
            <p>
               108 Adam Street <br>
              Dublin Ireland<br>
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Reservations</h4>
            <p>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat: 11AM</strong> - 23PM<br>
              Sunday: Closed
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Yummy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

app/views/menu/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">  
  <%= link_to "Restaurant Menu", root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link"%>
      </li>
      <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
      <li class="nav-item"><a class="nav-link" href="#chefs">Chefs</a></li>
      <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li> 
      

  <!-- if user_signed_in? -->
	<% if current_user %>
    <% if current_user.admin? || current_user.moderator?  %>
    <%# if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "Add Menu", new_menu_path, class:"nav-link"%>
      </li>
    <%end%>

      <li class="nav-item">
        <%= link_to "Show Menu", menus_path, class:"nav-link"%>
      </li>
      
      <li class="nav-item">
        <%= link_to "Edit Profile",  edit_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%#= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
        <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete, class:"nav-link" %>
      </li>
      </ul>

	  <!--####################################################-->
      <ul class="navbar-nav">
        <li class="nav-item text-light">
            <% if current_user.moderator? %>
              Hi moderator | <%= current_user.email %> 
              
              <% else %>

                Hi <%= current_user.role %> | <%= current_user.email %>
            <% end %>
          </li>
	   <!--####################################################-->
	  

  <!-- else-->
      <% else %>

      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
      </li>

  <!--end-->
  <% end %>

  
    </ul>
    
  </div>
</nav>

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>


  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
   
    <%= form.number_field :user_id, value:current_user.id, id: :menu_user_id, type: :hidden, class:"form-control" %>
  </div>
  <%=  %>
  <div>
    <%= form.submit class:" btn btn-secondary" %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <p class="lead">
    <strong class="font-weight-bold">Title:</strong>
    <%= menu.title %>
  </p>

  <p class="lead">
    <strong class="font-weight-bold">Ingredients:</strong>
    <%= menu.body %>
  </p>

  <p class="lead">
    <strong class="font-weight-bold">Price:</strong>
    <span>€</span><%= menu.price %>
  </p>
<hr class="my-4">
</div>

app/views/menus/edit.html.erb
<div class="card shadow-sm">
  <div class="card-header bg-info text-light ">
    <h1 class="text-center">Editing menu</h1>
  </div>
  <div class="card-body">
    <%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back to menus", menus_path, class:"btn btn-dark" %>
</div>
  </div>
</div>

app/views/menus/index.html.erb
<div class="jumbotron mb-5 shadow-sm bg-light shadow-sm">
  <h1 class="display-4 text-center font-weight-bold ">Menu</h1>
  <p class="lead">Our restaurant has<b> <%= Menu.public_count %></b> menus at the moment!</p>
  <%#=============================================================================================================%>
  <!--<form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    -->
    <form class="form-inline my-2 my-lg-0">
        <%= search_form_for @q do | f | %>
          <%= f.search_field :title_cont, class:"form-control mr-sm-2", placeholder:"Search by title" %>
          <%= f.submit "Search", class:"btn btn-outline-success my-2 my-sm-0" %>

        <% end %>
    </form>
  <%#=============================================================================================================%>
  <div id="menus">
  <% @menus.each do |menu| %>
  <% unless menu.archived? %>
  <hr class="my-4">
  
    <%= render menu %>
    <p>
      <%= link_to "Show this menu", menu, class: "btn btn-secondary" %>
    </p>
  <% end %>
  <%end%>
</div>
</div>



<%#= link_to "New menu", new_menu_path, class: "btn btn-primary mb-5" %>

app/views/menus/new.html.erb
<div class="card shadow-sm mb-5">
  <div class="card-header bg-info text-light ">
    <h1 class="text-center">New menu</h1>
  </div>
  <div class="card-body">
    <%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back to menus", menus_path, class:"btn btn-dark" %>
</div>
  </div>
</div>

app/views/menus/show.html.erb
<div class="jumbotron bg-light shadow-sm">
<h2 class="text-center mb-4">Menu</h2>
<%= render @menu %>

<div>
  <% if current_user %>
    <% if current_user.admin? || current_user.moderator? %>
        <%= link_to "Edit this menu", edit_menu_path(@menu), class: "btn btn-secondary" %> 
        <%= link_to "Back to menus", menus_path, class: "btn btn-dark" %>

        <%= button_to "Destroy this menu", @menu, method: :delete, class: "btn btn-danger mt-2" %>

      <% else %>
        <%#= link_to "Back to menus", menus_path, class: "btn btn-dark" %>
      <% end %>
      <% end %>
    </div>
    </div>
    <hr>
    <h2>Comments</h2>
    <%= render @menu.comments %>



  <div class="card mb-5">
    <div class="card-header">
      <h2>Add a comment:</h2>
    </div>
    <div class="card-body">
    <%= render 'comments/form' %>
    </div>
</div>